"""add token_blacklist table

Revision ID: 52cb3175f3ec
Revises: 252e1692f5a4
Create Date: 2026-05-11 21:26:04.758451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '52cb3175f3ec'
down_revision: Union[str, None] = '252e1692f5a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
