"""use enums for status fields and complete relationships

Revision ID: aabbb6d8362b
Revises: a88e01cfb395
Create Date: 2026-05-09 13:40:31.549284

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "aabbb6d8362b"
down_revision: Union[str, None] = "a88e01cfb395"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    ocr_status_enum = sa.Enum(
        "pending", "processing", "complete", "failed", name="ocrstatus"
    )
    ocr_status_enum.create(op.get_bind())

    medical_case_status_enum = sa.Enum(
        "pending", "processing", "complete", "failed", name="medicalcasestatus"
    )
    medical_case_status_enum.create(op.get_bind())

    op.alter_column(
        "lab_results",
        "ocr_status",
        existing_type=sa.VARCHAR(),
        type_=ocr_status_enum,
        existing_nullable=False,
        postgresql_using="ocr_status::ocrstatus",
    )
    op.alter_column(
        "medical_cases",
        "status",
        existing_type=sa.VARCHAR(),
        type_=medical_case_status_enum,
        existing_nullable=False,
        postgresql_using="status::medicalcasestatus",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    ocr_status_enum = sa.Enum(
        "pending", "processing", "complete", "failed", name="ocrstatus"
    )
    medical_case_status_enum = sa.Enum(
        "pending", "processing", "complete", "failed", name="medicalcasestatus"
    )

    op.alter_column(
        "medical_cases",
        "status",
        existing_type=medical_case_status_enum,
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.alter_column(
        "lab_results",
        "ocr_status",
        existing_type=ocr_status_enum,
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )

    medical_case_status_enum.drop(op.get_bind())
    ocr_status_enum.drop(op.get_bind())
    # ### end Alembic commands ###
