"""create users table

Revision ID: d5d4f2352c81
Revises: 90aeb7c687d7
Create Date: 2026-05-09 13:51:00.845313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd5d4f2352c81'
down_revision: Union[str, None] = '90aeb7c687d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
