"""add password_reset_tokens table

Revision ID: eefdbf628c7d
Revises: aabbb6d8362b
Create Date: 2026-05-09 20:15:41.170570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'eefdbf628c7d'
down_revision: Union[str, None] = 'aabbb6d8362b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
