DISCLAIMER: str = (
	"[Medical disclaimer — placeholder pending PM/medical-track sign-off] "
	"This interpretation is generated by an AI model and is not medical advice, "
	"a diagnosis, or a treatment plan. Always discuss your lab results with a "
	"licensed healthcare professional before making any decisions about your care."
)


def with_disclaimer(summary: str) -> str:
	"""Prepend the medical disclaimer to an LLM-generated summary."""
	cleaned = (summary or "").strip()
	if not cleaned:
		return DISCLAIMER
	return f"{DISCLAIMER}\n\n{cleaned}"
